@php
/* ── Language setup ──────────────────────────────────────────────────── */
$isAr = ($lang ?? app()->getLocale()) === 'ar';
$dir  = $isAr ? 'rtl' : 'ltr';
$locale = $isAr ? 'ar' : 'en';

$t = $isAr ? [
    /* header */
    'invoice_title_sales'    => 'فاتورة ضريبية مبسطة',
    'invoice_title_purchase' => 'فاتورة مشتريات',
    'invoice_title_cn'       => 'إشعار دائن',
    /* invoice details */
    'invoice_details'        => 'بيانات الفاتورة',
    'invoice_number'         => 'رقم الفاتورة',
    'invoice_type'           => 'نوع الفاتورة',
    'type_sales'             => 'مبيعات',
    'type_purchase'          => 'مشتريات',
    'type_cn'                => 'إشعار دائن',
    'issued_at'              => 'تاريخ الإصدار',
    'status'                 => 'الحالة',
    'status_paid'            => 'مدفوعة',
    'status_partial'         => 'مدفوعة جزئياً',
    'status_cancelled'       => 'ملغاة',
    'status_draft'           => 'مسودة',
    'reference_invoice'      => 'فاتورة مرجعية',
    /* member */
    'customer_info'          => 'بيانات العميل',
    'supplier_info'          => 'بيانات المورد',
    'name'                   => 'الاسم',
    'phone'                  => 'الجوال',
    'national_id'            => 'الهوية / الإقامة',
    'email'                  => 'البريد الإلكتروني',
    'supplier_id'            => 'رقم المورد',
    /* financials */
    'financial_summary'      => 'الملخص المالي',
    'description'            => 'البيان',
    'amount'                 => 'المبلغ',
    'subtotal'               => 'المجموع قبل الضريبة',
    'vat'                    => 'ضريبة القيمة المضافة',
    'total'                  => 'الإجمالي',
    /* payments */
    'payments'               => 'المدفوعات',
    'payment_method'         => 'طريقة الدفع',
    'date'                   => 'التاريخ',
    'cash'                   => 'نقدي',
    /* qr */
    'qr_label'               => 'رمز الاستجابة السريعة — هيئة الزكاة والضريبة والجمارك',
    /* notes */
    'notes'                  => 'ملاحظات',
    /* footer */
    'footer'                 => 'تم إنشاء هذه الفاتورة بواسطة النظام',
] : [
    /* header */
    'invoice_title_sales'    => 'Simplified Tax Invoice',
    'invoice_title_purchase' => 'Purchase Invoice',
    'invoice_title_cn'       => 'Credit Note',
    /* invoice details */
    'invoice_details'        => 'Invoice Details',
    'invoice_number'         => 'Invoice No.',
    'invoice_type'           => 'Invoice Type',
    'type_sales'             => 'Sales',
    'type_purchase'          => 'Purchase',
    'type_cn'                => 'Credit Note',
    'issued_at'              => 'Issue Date',
    'status'                 => 'Status',
    'status_paid'            => 'Paid',
    'status_partial'         => 'Partially Paid',
    'status_cancelled'       => 'Cancelled',
    'status_draft'           => 'Draft',
    'reference_invoice'      => 'Reference Invoice',
    /* member */
    'customer_info'          => 'Customer Info',
    'supplier_info'          => 'Supplier Info',
    'name'                   => 'Name',
    'phone'                  => 'Phone',
    'national_id'            => 'ID / Iqama',
    'email'                  => 'Email',
    'supplier_id'            => 'Supplier ID',
    /* financials */
    'financial_summary'      => 'Financial Summary',
    'description'            => 'Description',
    'amount'                 => 'Amount',
    'subtotal'               => 'Subtotal (before VAT)',
    'vat'                    => 'VAT',
    'total'                  => 'Total',
    /* payments */
    'payments'               => 'Payments',
    'payment_method'         => 'Payment Method',
    'date'                   => 'Date',
    'cash'                   => 'Cash',
    /* qr */
    'qr_label'               => 'QR Code — Zakat, Tax and Customs Authority (ZATCA)',
    /* notes */
    'notes'                  => 'Notes',
    /* footer */
    'footer'                 => 'This invoice was generated by the system',
];

$branchName = $isAr
    ? ($settings?->getRawOriginal('name_ar') ?: $settings?->getRawOriginal('name_en') ?: config('app.name'))
    : ($settings?->getRawOriginal('name_en') ?: $settings?->getRawOriginal('name_ar') ?: config('app.name'));

$invoiceTitle = match($invoice->type) {
    'sales'       => $t['invoice_title_sales'],
    'purchase'    => $t['invoice_title_purchase'],
    default       => $t['invoice_title_cn'],
};

$badgeClass = match($invoice->status) {
    'paid'      => 'badge-paid',
    'partial'   => 'badge-partial',
    'cancelled' => 'badge-cancelled',
    default     => 'badge-draft',
};
$statusLabel = match($invoice->status) {
    'paid'      => $t['status_paid'],
    'partial'   => $t['status_partial'],
    'cancelled' => $t['status_cancelled'],
    default     => $t['status_draft'],
};

$invoiceType = match($invoice->type) {
    'sales'    => $t['type_sales'],
    'purchase' => $t['type_purchase'],
    default    => $t['type_cn'],
};

/* For LTR: header number/date aligns right, labels align left */
$numAlign   = $isAr ? 'left'  : 'right';
$labelAlign = $isAr ? 'right' : 'left';
$amountAlign = $isAr ? 'left' : 'right';
$notesBorder = $isAr ? 'border-right' : 'border-left';
@endphp
<!DOCTYPE html>
<html dir="{{ $dir }}" lang="{{ $locale }}">
<head>
<meta charset="UTF-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title>{{ $invoice->invoice_number }}</title>
<style>
    * { margin: 0; padding: 0; box-sizing: border-box; }

    body {
        font-family: DejaVu Sans, Arial, sans-serif;
        font-size: 12px;
        color: #222;
        background: #fff;
        direction: {{ $dir }};
    }

    /* ── Header ── */
    .header {
        background-color: #1a3a5c;
        padding: 18px 24px;
        width: 100%;
    }
    .header table { width: 100%; border-collapse: collapse; }
    .header td { vertical-align: middle; color: #ffffff; }
    .header .branch-name   { font-size: 20px; font-weight: bold; color: #ffffff; }
    .header .invoice-title { font-size: 14px; margin-top: 4px; color: #ffffff; }
    .header .invoice-number { font-size: 22px; font-weight: bold; color: #ffffff; text-align: {{ $numAlign }}; }
    .header .invoice-date   { font-size: 12px; color: #ffffff; text-align: {{ $numAlign }}; }

    /* ── Status badges ── */
    .badge {
        display: inline-block;
        padding: 3px 10px;
        border-radius: 4px;
        font-size: 11px;
        font-weight: bold;
        color: #fff;
    }
    .badge-draft     { background-color: #6c757d; }
    .badge-partial   { background-color: #fd7e14; }
    .badge-paid      { background-color: #28a745; }
    .badge-cancelled { background-color: #dc3545; }

    /* ── Sections ── */
    .section { padding: 14px 24px; }
    .section-title {
        font-size: 12px;
        font-weight: bold;
        color: #1a3a5c;
        border-bottom: 2px solid #1a3a5c;
        padding-bottom: 4px;
        margin-bottom: 10px;
    }

    /* ── Info grid ── */
    .info-table { width: 100%; border-collapse: collapse; }
    .info-table td { padding: 5px 8px; font-size: 11px; }
    .info-table .label { color: #555; width: 40%; text-align: {{ $labelAlign }}; }
    .info-table .value { font-weight: bold; color: #222; }

    /* ── Two-column layout ── */
    .two-col { width: 100%; border-collapse: collapse; }
    .two-col td { width: 50%; vertical-align: top; padding: 0 8px; }

    /* ── Financials ── */
    .fin-table { width: 100%; border-collapse: collapse; margin-top: 4px; }
    .fin-table th {
        background-color: #1a3a5c;
        color: #fff;
        padding: 7px 10px;
        font-size: 11px;
        text-align: {{ $labelAlign }};
    }
    .fin-table th.amount-col,
    .fin-table td.amount-col { text-align: {{ $amountAlign }}; }
    .fin-table td {
        padding: 7px 10px;
        font-size: 12px;
        border-bottom: 1px solid #e8e8e8;
    }
    .fin-table tr:last-child td { border-bottom: none; }
    .fin-table .total-row td {
        background-color: #eef2f7;
        font-weight: bold;
        font-size: 13px;
    }

    /* ── Payments ── */
    .pay-table { width: 100%; border-collapse: collapse; margin-top: 4px; }
    .pay-table th {
        background-color: #2e7d32;
        color: #fff;
        padding: 6px 10px;
        font-size: 11px;
        text-align: {{ $labelAlign }};
    }
    .pay-table td {
        padding: 6px 10px;
        font-size: 11px;
        border-bottom: 1px solid #e8e8e8;
    }
    .pay-table tr:last-child td { border-bottom: none; }
    .pay-table .amount-col { text-align: {{ $amountAlign }}; }

    /* ── QR code ── */
    .qr-section {
        padding: 8px 24px 0;
        text-align: {{ $isAr ? 'right' : 'left' }};
    }
    .qr-section img {
        width: 180px;
        height: 180px;
    }
    .qr-label {
        font-size: 9px;
        color: #999;
        margin-top: 3px;
    }

    /* ── Notes ── */
    .notes-box {
        background-color: #f9f9f9;
        {{ $notesBorder }}: 4px solid #1a3a5c;
        padding: 8px 12px;
        font-size: 11px;
        color: #444;
        margin: 0 24px 12px;
    }

    /* ── Footer ── */
    .footer {
        background-color: #f0f4f8;
        text-align: center;
        padding: 8px 24px;
        font-size: 10px;
        color: #555;
        border-top: 1px solid #ccc;
        position: fixed;
        bottom: 0;
        width: 100%;
    }
</style>
</head>
<body>

{{-- ── Header ──────────────────────────────────────────────────────── --}}
<div class="header">
    <table>
        <tr>
            <td>
                <div class="branch-name">{{ $branchName }}</div>
                <div class="invoice-title">{{ $invoiceTitle }}</div>
            </td>
            <td style="text-align:{{ $numAlign }};">
                <div class="invoice-number">{{ $invoice->invoice_number }}</div>
                <div class="invoice-date">
                    {{ $invoice->issued_at ? $invoice->issued_at->format('Y-m-d') : now()->format('Y-m-d') }}
                </div>
            </td>
        </tr>
    </table>
</div>

{{-- ── Invoice details + Member info (two-column) ─────────────────── --}}
<div class="section">
    <table class="two-col">
        <tr>
            {{-- Invoice details --}}
            <td>
                <div class="section-title">{{ $t['invoice_details'] }}</div>
                <table class="info-table">
                    <tr>
                        <td class="label">{{ $t['invoice_number'] }}</td>
                        <td class="value">{{ $invoice->invoice_number }}</td>
                    </tr>
                    <tr>
                        <td class="label">{{ $t['invoice_type'] }}</td>
                        <td class="value">{{ $invoiceType }}</td>
                    </tr>
                    <tr>
                        <td class="label">{{ $t['issued_at'] }}</td>
                        <td class="value">{{ $invoice->issued_at ? $invoice->issued_at->format('Y-m-d') : '—' }}</td>
                    </tr>
                    <tr>
                        <td class="label">{{ $t['status'] }}</td>
                        <td class="value">
                            <span class="badge {{ $badgeClass }}">{{ $statusLabel }}</span>
                        </td>
                    </tr>
                    @if($invoice->reference_invoice_id)
                    <tr>
                        <td class="label">{{ $t['reference_invoice'] }}</td>
                        <td class="value">{{ optional($invoice->originalInvoice)->invoice_number ?? '#'.$invoice->reference_invoice_id }}</td>
                    </tr>
                    @endif
                </table>
            </td>

            {{-- Member / Supplier info --}}
            <td>
                @if($invoice->member)
                <div class="section-title">{{ $t['customer_info'] }}</div>
                <table class="info-table">
                    <tr>
                        <td class="label">{{ $t['name'] }}</td>
                        <td class="value">{{ $invoice->member->name }}</td>
                    </tr>
                    @if($invoice->member->phone)
                    <tr>
                        <td class="label">{{ $t['phone'] }}</td>
                        <td class="value">{{ $invoice->member->phone }}</td>
                    </tr>
                    @endif
                    @if($invoice->member->national_id)
                    <tr>
                        <td class="label">{{ $t['national_id'] }}</td>
                        <td class="value">{{ $invoice->member->national_id }}</td>
                    </tr>
                    @endif
                    @if($invoice->member->email)
                    <tr>
                        <td class="label">{{ $t['email'] }}</td>
                        <td class="value">{{ $invoice->member->email }}</td>
                    </tr>
                    @endif
                </table>
                @elseif($invoice->supplier_id)
                <div class="section-title">{{ $t['supplier_info'] }}</div>
                <table class="info-table">
                    <tr>
                        <td class="label">{{ $t['supplier_id'] }}</td>
                        <td class="value">{{ $invoice->supplier_id }}</td>
                    </tr>
                </table>
                @endif
            </td>
        </tr>
    </table>
</div>

{{-- ── Financial summary ────────────────────────────────────────────── --}}
<div class="section">
    <div class="section-title">{{ $t['financial_summary'] }}</div>
    <table class="fin-table">
        <thead>
            <tr>
                <th>{{ $t['description'] }}</th>
                <th class="amount-col">{{ $t['amount'] }}</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ $t['subtotal'] }}</td>
                <td class="amount-col">{{ number_format($invoice->subtotal, 2) }}</td>
            </tr>
            <tr>
                <td>{{ $t['vat'] }} ({{ $invoice->vat_rate }}%)</td>
                <td class="amount-col">{{ number_format($invoice->vat_amount, 2) }}</td>
            </tr>
            <tr class="total-row">
                <td>{{ $t['total'] }}</td>
                <td class="amount-col">{{ number_format($invoice->total, 2) }}</td>
            </tr>
        </tbody>
    </table>
</div>

{{-- ── Payments ─────────────────────────────────────────────────────── --}}
@if($invoice->moneyBoxes->isNotEmpty())
<div class="section">
    <div class="section-title">{{ $t['payments'] }}</div>
    <table class="pay-table">
        <thead>
            <tr>
                <th>#</th>
                <th>{{ $t['payment_method'] }}</th>
                <th>{{ $t['date'] }}</th>
                <th class="amount-col">{{ $t['amount'] }}</th>
            </tr>
        </thead>
        <tbody>
            @foreach($invoice->moneyBoxes as $mb)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $mb->pay_type?->name ?? $t['cash'] }}</td>
                <td>{{ $mb->created_at?->format('Y-m-d') ?? '—' }}</td>
                <td class="amount-col">{{ number_format($mb->amount, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>
@endif

{{-- ── ZATCA QR code ────────────────────────────────────────────────── --}}
@if($invoice->zatcaBillingInvoice && $invoice->zatcaBillingInvoice->zatca_qr_code)
<div class="qr-section">
    <img src="data:image/png;base64,{{ $invoice->zatcaBillingInvoice->zatca_qr_code }}"
         alt="ZATCA QR Code" width="180" height="180">
    <div class="qr-label">{{ $t['qr_label'] }}</div>
</div>
@endif

{{-- ── Notes ───────────────────────────────────────────────────────── --}}
@if($invoice->notes)
<div class="notes-box">
    <strong>{{ $t['notes'] }}:</strong> {{ $invoice->notes }}
</div>
@endif

{{-- ── Footer ───────────────────────────────────────────────────────── --}}
<div class="footer">
    {{ $t['footer'] }} &mdash; {{ now()->format('Y-m-d H:i') }}
</div>

</body>
</html>
